
const articles = [
    {
        id: 1,
        title: "Sử dụng và Tác động của Y học từ xa",
        summary: "Bài báo này xem xét việc sử dụng y học từ xa trong các hệ thống y tế, tập trung vào việc sử dụng, chi tiêu và chất lượng để định hình các chính sách thanh toán và yêu cầu trong tương lai.",
        full_content: "\n            <h1 class=\"text-3xl font-bold text-gray-900 mb-4\">Sử dụng và Tác động của Y học từ xa (2024)</h1>\n            <p class=\"text-lg text-gray-700 mb-4\">\n                Y học từ xa đã nổi lên như một công cụ mạnh mẽ trong việc cung cấp dịch vụ chăm sóc sức khỏe, đặc biệt là trong bối cảnh đại dịch COVID-19. \n                Bài báo này đi sâu vào các xu hướng sử dụng y học từ xa, phân tích chi tiêu và đánh giá chất lượng dịch vụ. \n                Kết quả nghiên cứu sẽ là cơ sở quan trọng để các nhà hoạch định chính sách xây dựng các quy định thanh toán và các yêu cầu pháp lý trong tương lai, \n                nhằm tối ưu hóa lợi ích của y học từ xa và đảm bảo an toàn cho bệnh nhân.\n            </p>\n            <img class=\"w-full h-auto object-cover rounded-lg my-6\" src=\"https://images.unsplash.com/photo-1584515933487-779824d29309\" alt=\"Y học từ xa\">\n            <h2 class=\"text-2xl font-bold text-gray-800 mt-6 mb-2\">Những thách thức và cơ hội</h2>\n            <p class=\"text-gray-700\">\n                Mặc dù có nhiều lợi ích, y học từ xa cũng đối mặt với không ít thách thức như vấn đề bảo mật thông tin, \n                khả năng tiếp cận công nghệ của người dân và sự cần thiết của việc thăm khám trực tiếp trong một số trường hợp. \n                Tuy nhiên, với sự phát triển không ngừng của công nghệ, y học từ xa hứa hẹn sẽ tiếp tục là một phần không thể thiếu của hệ thống y tế hiện đại.\n            </p>\n        ",
        image: "https://images.unsplash.com/photo-1584515933487-779824d29309?q=80&w=2070&auto=format&fit=crop"
    },
    {
        id: 2,
        title: "Thách thức trong Điều trị Nghiện ở Thanh thiếu niên",
        summary: "Nghiên cứu chỉ ra sự tiếp cận không đồng đều, danh sách chờ dài và chi phí cao liên quan đến điều trị nghiện nội trú cho thanh thiếu niên ở Hoa Kỳ.",
        full_content: "\n            <h1 class=\"text-3xl font-bold text-gray-900 mb-4\">Thách thức trong Điều trị Nghiện ở Thanh thiếu niên (2024)</h1>\n            <p class=\"text-lg text-gray-700 mb-4\">\n                Nghiện chất ở lứa tuổi thanh thiếu niên là một vấn đề sức khỏe cộng đồng nghiêm trọng. \n                Nghiên cứu mới đây cho thấy những rào cản lớn trong việc tiếp cận điều trị nội trú, bao gồm sự phân bổ không đồng đều các cơ sở điều trị, \n                thời gian chờ đợi kéo dài và chi phí điều trị cao. Điều này đặt ra yêu cầu cấp thiết về việc cải thiện hệ thống chăm sóc sức khỏe tâm thần và cai nghiện cho giới trẻ.\n            </p>\n            <img class=\"w-full h-auto object-cover rounded-lg my-6\" src=\"https://images.unsplash.com/photo-1593121923439-1099f253d348\" alt=\"Thanh thiếu niên\">\n            <h2 class=\"text-2xl font-bold text-gray-800 mt-6 mb-2\">Giải pháp đề xuất</h2>\n            <p class=\"text-gray-700\">\n                Các chuyên gia đề xuất một số giải pháp như tăng cường đầu tư vào các trung tâm điều trị công, \n                đơn giản hóa thủ tục hành chính và mở rộng phạm vi bảo hiểm y tế cho các dịch vụ cai nghiện. \n                Việc can thiệp sớm và hiệu quả sẽ giúp thanh thiếu niên vượt qua giai đoạn khó khăn và có một tương lai tươi sáng hơn.\n            </p>\n        ",
        image: "https://images.unsplash.com/photo-1593121923439-1099f253d348?q=80&w=2070&auto=format&fit=crop"
    },
    {
        id: 3,
        title: "Hạn chế Thuốc kê đơn trong Kế hoạch Medicare Phần D",
        summary: "Một phân tích cho thấy sự gia tăng đáng kể các hạn chế sử dụng, như ủy quyền trước và liệu pháp từng bước, đối với thuốc kê đơn trong các kế hoạch Medicare Phần D từ năm 2011 đến 2020.",
        full_content: "\n            <h1 class=\"text-3xl font-bold text-gray-900 mb-4\">Hạn chế Thuốc kê đơn trong Kế hoạch Medicare Phần D (2024)</h1>\n            <p class=\"text-lg text-gray-700 mb-4\">\n                Phân tích mới nhất về chương trình Medicare Phần D của Hoa Kỳ đã chỉ ra một xu hướng đáng lo ngại: \n                sự gia tăng các rào cản trong việc tiếp cận thuốc kê đơn. Các biện pháp như yêu cầu ủy quyền trước (prior authorization) \n                và liệu pháp từng bước (step therapy) ngày càng trở nên phổ biến, gây khó khăn cho bệnh nhân trong việc nhận được loại thuốc cần thiết một cách kịp thời.\n            </p>\n            <img class=\"w-full h-auto object-cover rounded-lg my-6\" src=\"https://images.unsplash.com/photo-1584362916299-01b86a8b386d\" alt=\"Thuốc kê đơn\">\n            <h2 class=\"text-2xl font-bold text-gray-800 mt-6 mb-2\">Tác động đến bệnh nhân</h2>\n            <p class=\"text-gray-700\">\n                Những hạn chế này có thể dẫn đến việc trì hoãn điều trị, giảm tuân thủ phác đồ và thậm chí làm xấu đi tình trạng sức khỏe của bệnh nhân. \n                Bài báo kêu gọi một sự cân bằng giữa việc kiểm soát chi phí và đảm bảo quyền lợi của người bệnh, \n                đề xuất các giải pháp nhằm minh bạch hóa quy trình và giảm bớt gánh nặng hành chính cho cả bệnh nhân và bác sĩ.\n            </p>\n        ",
        image: "https://images.unsplash.com/photo-1584362916299-01b86a8b386d?q=80&w=2070&auto=format&fit=crop"
    },
    {
        id: 4,
        title: "Đóng cửa Nhà thuốc ở Hoa Kỳ",
        summary: "Một báo cáo chỉ ra rằng số lượng nhà thuốc đóng cửa nhiều hơn số lượng mở mới từ năm 2018 đến 2021, với các nhà thuốc độc lập và những nhà thuốc ở cộng đồng người da đen và Latinh có nguy cơ cao nhất.",
        full_content: "\n            <h1 class=\"text-3xl font-bold text-gray-900 mb-4\">Đóng cửa Nhà thuốc ở Hoa Kỳ (2024)</h1>\n            <p class=\"text-lg text-gray-700 mb-4\">\n                Một xu hướng đáng báo động đang diễn ra trên khắp nước Mỹ: số lượng nhà thuốc đang giảm dần. \n                Báo cáo gần đây cho thấy, từ năm 2018 đến 2021, số nhà thuốc đóng cửa đã vượt qua số nhà thuốc mới được mở. \n                Tình trạng này ảnh hưởng nặng nề nhất đến các nhà thuốc độc lập và các cộng đồng thiểu số, \n                tạo ra những \"sa mạc nhà thuốc\" (pharmacy deserts) và hạn chế khả năng tiếp cận thuốc men của người dân.\n            </p>\n            <img class=\"w-full h-auto object-cover rounded-lg my-6\" src=\"https://images.unsplash.com/photo-1583316175804-1583c85b3551\" alt=\"Nhà thuốc\">\n            <h2 class=\"text-2xl font-bold text-gray-800 mt-6 mb-2\">Nguyên nhân và hậu quả</h2>\n            <p class=\"text-gray-700\">\n                Các yếu tố như áp lực cạnh tranh từ các chuỗi lớn, chính sách thanh toán bảo hiểm phức tạp và gánh nặng tài chính \n                đã đẩy nhiều nhà thuốc độc lập đến bờ vực phá sản. Hậu quả là người dân, đặc biệt là người cao tuổi và người có bệnh mãn tính, \n                sẽ gặp nhiều khó khăn hơn trong việc duy trì sức khỏe của mình.\n            </p>\n        ",
        image: "https://images.unsplash.com/photo-1583316175804-1583c85b3551?q=80&w=2070&auto=format&fit=crop"
    },
    {
        id: 5,
        title: "Chuyển đổi sang Chế độ ăn dựa trên thực vật",
        summary: "Bài viết này cung cấp các mẹo và hướng dẫn thực tế cho những người muốn giảm tiêu thụ thịt và sữa, dù là để ăn chay hoàn toàn hay chỉ đơn giản là kết hợp nhiều thực phẩm từ thực vật hơn.",
        full_content: "\n            <h1 class=\"text-3xl font-bold text-gray-900 mb-4\">Chuyển đổi sang Chế độ ăn dựa trên thực vật (2021)</h1>\n            <p class=\"text-lg text-gray-700 mb-4\">\n                Ngày càng có nhiều người quan tâm đến chế độ ăn dựa trên thực vật vì những lợi ích sức khỏe và môi trường mà nó mang lại. \n                Bài viết này là một hướng dẫn toàn diện, cung cấp những lời khuyên hữu ích cho những ai muốn bắt đầu hành trình này. \n                Từ việc thay thế dần dần các sản phẩm từ động vật đến việc khám phá các công thức nấu ăn mới, \n                bạn sẽ tìm thấy những cách tiếp cận linh hoạt và dễ thực hiện.\n            </p>\n            <img class=\"w-full h-auto object-cover rounded-lg my-6\" src=\"https://images.unsplash.com/photo-1540914124281-3425879413d9\" alt=\"Chế độ ăn thực vật\">\n            <h2 class=\"text-2xl font-bold text-gray-800 mt-6 mb-2\">Lợi ích và lưu ý</h2>\n            <p class=\"text-gray-700\">\n                Một chế độ ăn giàu thực vật có thể giúp giảm nguy cơ mắc các bệnh tim mạch, tiểu đường tuýp 2 và một số loại ung thư. \n                Tuy nhiên, điều quan trọng là phải đảm bảo cung cấp đủ các chất dinh dưỡng thiết yếu như vitamin B12, sắt và canxi. \n                Bài viết cũng đưa ra những gợi ý về các nguồn thực phẩm bổ sung để có một chế độ ăn cân bằng và lành mạnh.\n            </p>\n        ",
        image: "https://images.unsplash.com/photo-1540914124281-3425879413d9?q=80&w=2070&auto=format&fit=crop"
    },
    {
        id: 6,
        title: "Lợi ích của Giấm táo đối với nam giới",
        summary: "Khám phá các lợi ích sức khỏe khác nhau của giấm táo, bao gồm vai trò tiềm năng của nó trong việc giảm cân và tác động của nó đối với sức khỏe nam giới.",
        full_content: "\n            <h1 class=\"text-3xl font-bold text-gray-900 mb-4\">Lợi ích của Giấm táo đối với nam giới (2023)</h1>\n            <p class=\"text-lg text-gray-700 mb-4\">\n                Giấm táo từ lâu đã được biết đến như một phương thuốc tự nhiên với nhiều công dụng. \n                Bài viết này tập trung vào những lợi ích tiềm năng của giấm táo đối với sức khỏe nam giới. \n                Các nghiên cứu cho thấy giấm táo có thể hỗ trợ kiểm soát đường huyết, cải thiện sức khỏe tim mạch và thậm chí góp phần vào nỗ lực giảm cân.\n            </p>\n            <img class=\"w-full h-auto object-cover rounded-lg my-6\" src=\"https://images.unsplash.com/photo-1550985607-b69d8f5a38da\" alt=\"Giấm táo\">\n            <h2 class=\"text-2xl font-bold text-gray-800 mt-6 mb-2\">Cách sử dụng an toàn</h2>\n            <p class=\"text-gray-700\">\n                Mặc dù có nhiều lợi ích, việc sử dụng giấm táo cũng cần đúng cách để tránh các tác dụng phụ không mong muốn như hại men răng hoặc kích ứng dạ dày. \n                Bài viết cung cấp những hướng dẫn cụ thể về liều lượng và cách pha loãng giấm táo để đảm bảo an toàn và hiệu quả khi sử dụng.\n            </p>\n        ",
        image: "https://images.unsplash.com/photo-1550985607-b69d8f5a38da?q=80&w=2070&auto=format&fit=crop"
    },
    {
        id: 7,
        title: "Thực phẩm giúp loại bỏ đờm",
        summary: "Bài báo này xác định các loại thực phẩm cụ thể có thể giúp giảm đờm quá mức, một triệu chứng phổ biến của dị ứng hoặc cảm lạnh thông thường, và đề xuất các loại thực phẩm nên tránh.",
        full_content: "\n            <h1 class=\"text-3xl font-bold text-gray-900 mb-4\">Thực phẩm giúp loại bỏ đờm (2023)</h1>\n            <p class=\"text-lg text-gray-700 mb-4\">\n                Đờm là một triệu chứng khó chịu thường gặp khi bị cảm lạnh, cúm hoặc dị ứng. \n                May mắn là một số loại thực phẩm có thể giúp làm loãng và loại bỏ đờm một cách tự nhiên. \n                Bài viết này liệt kê các loại thực phẩm hữu ích như gừng, tỏi, dứa và các loại rau củ quả giàu vitamin C.\n            </p>\n            <img class=\"w-full h-auto object-cover rounded-lg my-6\" src=\"https://images.unsplash.com/photo-1522184216316-3c25379f9760\" alt=\"Thực phẩm\">\n            <h2 class=\"text-2xl font-bold text-gray-800 mt-6 mb-2\">Những thực phẩm cần tránh</h2>\n            <p class=\"text-gray-700\">\n                Bên cạnh những thực phẩm nên ăn, bài viết cũng chỉ ra những loại thực phẩm có thể làm tình trạng đờm trở nên tồi tệ hơn, \n                chẳng hạn như các sản phẩm từ sữa, đồ chiên rán và thực phẩm chế biến sẵn. \n                Việc điều chỉnh chế độ ăn uống một cách hợp lý sẽ giúp bạn cảm thấy dễ chịu hơn và nhanh chóng phục hồi sức khỏe.\n            </p>\n        ",
        image: "https://images.unsplash.com/photo-1522184216316-3c25379f9760?q=80&w=2070&auto=format&fit=crop"
    },
    {
        id: 8,
        title: "Hướng dẫn tự nhiên về Thực phẩm chữa bệnh",
        summary: "Thảo luận về cách một số loại thực phẩm có hình dạng giống với các bộ phận cơ thể mà chúng có lợi, chẳng hạn như quả óc chó cho não và cà rốt cho mắt, gợi ý một mối liên hệ tự nhiên giữa thực phẩm và việc chữa bệnh.",
        full_content: "\n            <h1 class=\"text-3xl font-bold text-gray-900 mb-4\">Hướng dẫn tự nhiên về Thực phẩm chữa bệnh (2024)</h1>\n            <p class=\"text-lg text-gray-700 mb-4\">\n                Có một triết lý thú vị cho rằng thiên nhiên đã cho chúng ta những gợi ý về công dụng của thực phẩm thông qua hình dạng của chúng. \n                Bài viết này khám phá mối liên hệ hấp dẫn giữa hình dạng của thực phẩm và các bộ phận cơ thể mà chúng mang lại lợi ích. \n                Ví dụ, quả óc chó trông giống như một bộ não thu nhỏ và rất giàu axit béo omega-3 tốt cho não. \n                Cà rốt cắt lát trông giống như mắt người và chứa nhiều beta-carotene, một chất chống oxy hóa quan trọng cho thị lực.\n            </p>\n            <img class=\"w-full h-auto object-cover rounded-lg my-6\" src=\"https://images.unsplash.com/photo-1498837167922-ddd27525d352\" alt=\"Thực phẩm chữa bệnh\">\n            <h2 class=\"text-2xl font-bold text-gray-800 mt-6 mb-2\">Khoa học đằng sau</h2>\n            <p class=\"text-gray-700\">\n                Mặc dù đây là một cách tiếp cận thú vị, bài viết cũng đi sâu vào cơ sở khoa học đằng sau những lợi ích này. \n                Nó giải thích cách các chất dinh dưỡng cụ thể trong từng loại thực phẩm tác động đến các cơ quan tương ứng, \n                cung cấp một cái nhìn toàn diện và đáng tin cậy về sức mạnh chữa lành của thực phẩm.\n            </p>\n        ",
        image: "https://images.unsplash.com/photo-1498837167922-ddd27525d352?q=80&w=2070&auto=format&fit=crop"
    },
    {
        id: 9,
        title: "Thời điểm uống cà phê buổi sáng",
        summary: "Giải thích cách thời gian uống cà phê trong ngày có thể ảnh hưởng đến tiêu hóa và mức độ hormone, cung cấp cái nhìn sâu sắc về việc tối ưu hóa lượng cà phê nạp vào để có sức khỏe tốt.",
        full_content: "\n            <h1 class=\"text-3xl font-bold text-gray-900 mb-4\">Thời điểm uống cà phê buổi sáng (2024)</h1>\n            <p class=\"text-lg text-gray-700 mb-4\">\n                Đối với nhiều người, một tách cà phê là không thể thiếu để bắt đầu ngày mới. \n                Tuy nhiên, thời điểm bạn uống cà phê có thể ảnh hưởng đến hiệu quả của nó và cả sức khỏe của bạn. \n                Bài viết này phân tích mối quan hệ giữa việc uống cà phê và nồng độ cortisol, hormone căng thẳng của cơ thể.\n            </p>\n            <img class=\"w-full h-auto object-cover rounded-lg my-6\" src=\"https://images.unsplash.com/photo-1559496417-e7f25cb247f3\" alt=\"Uống cà phê\">\n            <h2 class=\"text-2xl font-bold text-gray-800 mt-6 mb-2\">Thời điểm vàng</h2>\n            <p class=\"text-gray-700\">\n                Các chuyên gia khuyên rằng thời điểm tốt nhất để uống cà phê không phải là ngay sau khi thức dậy, \n                mà là khoảng từ 9:30 đến 11:30 sáng, khi nồng độ cortisol tự nhiên bắt đầu giảm. \n                Uống cà phê vào thời điểm này sẽ giúp bạn tận dụng tối đa tác dụng tỉnh táo của caffeine mà không làm ảnh hưởng đến nhịp sinh học tự nhiên của cơ thể.\n            </p>\n        ",
        image: "https://images.unsplash.com/photo-1559496417-e7f25cb247f3?q=80&w=2070&auto=format&fit=crop"
    },
    {
        id: 10,
        title: "Bệnh tim ở phụ nữ",
        summary: "Bài báo này đề cập đến vấn đề quan trọng về bệnh tim là nguyên nhân gây tử vong hàng đầu ở phụ nữ, thường bị chẩn đoán và điều trị dưới mức, nhấn mạnh sự cần thiết phải nâng cao nhận thức và chăm sóc tốt hơn.",
        full_content: "\n            <h1 class=\"text-3xl font-bold text-gray-900 mb-4\">Bệnh tim ở phụ nữ (2024)</h1>\n            <p class=\"text-lg text-gray-700 mb-4\">\n                Bệnh tim mạch thường được coi là một vấn đề sức khỏe của nam giới, nhưng thực tế, đây lại là nguyên nhân gây tử vong hàng đầu ở phụ nữ. \n                Bài báo này nhấn mạnh rằng các triệu chứng bệnh tim ở phụ nữ có thể khác biệt so với nam giới, \n                dẫn đến việc chẩn đoán và điều trị chậm trễ.\n            </p>\n            <img class=\"w-full h-auto object-cover rounded-lg my-6\" src=\"https://images.unsplash.com/photo-1505751172876-7afd375c3434\" alt=\"Bệnh tim\">\n            <h2 class=\"text-2xl font-bold text-gray-800 mt-6 mb-2\">Nâng cao nhận thức</h2>\n            <p class=\"text-gray-700\">\n                Việc nhận biết các dấu hiệu cảnh báo sớm như mệt mỏi bất thường, khó thở, đau lưng hoặc hàm là vô cùng quan trọng. \n                Bài viết kêu gọi sự quan tâm nhiều hơn từ cả bệnh nhân và các chuyên gia y tế để cải thiện tỷ lệ sống sót và chất lượng cuộc sống cho phụ nữ mắc bệnh tim.\n            </p>\n        ",
        image: "https://images.unsplash.com/photo-1505751172876-7afd375c3434?q=80&w=2070&auto=format&fit=crop"
    }
];
